controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
  path: /api/login_check

Users:
  resource: App\Controller\UsersController
  prefix: /api

Formation:
  resource: App\Controller\FormationController
  prefix: /api

DemandeInscription:
  resource: App\Controller\DemandeInscriptionController
  prefix: /api

CentresDeFormation:
  resource: App\Controller\CentresDeFormationController
  prefix: /api

Formateurs:
  resource: App\Controller\FormateursController
  prefix: /api

Etudiant:
  resource: App\Controller\EtudiantController
  prefix: /api

Abonnement:
  resource: App\Controller\AbonnementController
  prefix: /api

Paiement:
  resource: App\Controller\PaiementController
  prefix: /api

PackDeFormations:
  resource: App\Controller\PackDeFormationsController
  prefix: /api
